name: Run Swift Test Cases

on:
  workflow_dispatch:

jobs:
  test-swift-code:
    runs-on: macos-latest  # Required for Swift execution
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Swift
        run: swift --version

      - name: Fetch submitted Swift file
        run: |
          curl -o submission.swift "GOOGLE_DRIVE_FILE_URL"

      - name: Run Swift Test Cases
        run: |
          swift test.swift submission.swift > output.txt
          cat output.txt

      - name: Upload Results
        uses: actions/upload-artifact@v3
        with:
          name: swift-test-results
          path: output.txt
